import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Share } from '@capacitor/share';
import { IonButton, IonHeader, IonTitle, IonToolbar } from '@ionic/react';
import { Capacitor } from '@capacitor/core';

export default function Home () {
  const share = async () => {
    await Share.share({
      title: 'Simons YT Channel',
      text: 'Learn to build awesome mobile apps!',
      url: 'https://www.youtube.com/simongrimmdev_',
      dialogTitle: 'Share with freiends'
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {Capacitor.isNativePlatform() && (
        <IonHeader>
          <IonToolbar color="primary">
            <IonTitle>Simons Capacitor App</IonTitle>
          </IonToolbar>
        </IonHeader>
      )}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Simonics!</a>
        </h1>
        <IonButton color="success" onClick={() => share()}>
          Share now!
        </IonButton>
      </main>
    </div>
  );
}